apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-4
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 최신 정책
  hostPath:
    path: /var/log/kafka-data-4
