apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2  # EBS 볼륨 타입 (일반적으로 gp2)
  fsType: ext4  # 파일 시스템 타입
reclaimPolicy: Delete  # PVC 삭제 시 PV도 삭제
